#!/bin/sh
# Prints the Homebrew formula for one quet release.
#
#   homebrew-formula.sh <version> <download-base-url> <SHA256SUMS>
#
# <download-base-url> is where the release assets live, for example
# https://github.com/8bu/quet/releases/download/v0.2.0. Each platform's
# checksum is read from <SHA256SUMS>, the file `make release` writes, so the
# formula always matches the binaries it points at.
set -eu

if [ "$#" -ne 3 ]; then
	echo "usage: $0 <version> <download-base-url> <SHA256SUMS>" >&2
	exit 2
fi
version=$1
base=$2
sums=$3

# sha prints the checksum of one asset, failing if the sums file lacks it.
sha() {
	s=$(awk -v f="$1" '$2 == f { print $1 }' "$sums")
	if [ -z "$s" ]; then
		echo "homebrew-formula: $1 is not listed in $sums" >&2
		exit 1
	fi
	printf '%s' "$s"
}

darwin_arm64=$(sha quet_darwin_arm64)
darwin_amd64=$(sha quet_darwin_amd64)
linux_arm64=$(sha quet_linux_arm64)
linux_amd64=$(sha quet_linux_amd64)

cat <<EOF
# Generated by .github/scripts/homebrew-formula.sh in github.com/8bu/quet for
# each release. Do not edit by hand: the next release overwrites it.
class Quet < Formula
  desc "Fast, keyboard-first TUI for reviewing and curating text corpora"
  homepage "https://github.com/8bu/quet"
  version "${version}"

  on_macos do
    on_arm do
      url "${base}/quet_darwin_arm64"
      sha256 "${darwin_arm64}"
    end
    on_intel do
      url "${base}/quet_darwin_amd64"
      sha256 "${darwin_amd64}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/quet_linux_arm64"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "${base}/quet_linux_amd64"
      sha256 "${linux_amd64}"
    end
  end

  def install
    bin.install Dir["quet_*"].first => "quet"
  end

  test do
    assert_match "quet #{version}", shell_output("#{bin}/quet --version")
  end
end
EOF
